server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  application:
    name: account
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/account_service
#    username: account
#    password: account@1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        enable_lazy_load_no_trans: true
#    open-in-view: false
#    show-sql: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

  profiles:
      active: production
  config:
      import: optional:configserver:http://localhost:8071
  cloud:
    compatibility-verifier:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"