spring:
  application:
    name: config
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/nhaserey/bank-config-server-private
            #- https://github.com/nhaserey/config
          username: nhaserey
          password: Token
          clone-on-start: true
          default-label: sereynha
encrypt:
    key: vrAV66F20£mIyG09iUKsrYUME?03yA3AuPyU
server:
  port: 8071
management:
  endpoints:
    web:
      exposure:
        include: '*'