account:
  msg: Welcome to the Bank Account Default application
  build-version: 3
  mailDetails:
    hostName: default-account@bank.com
    port: 9000
    from: default-account@bank.com
    subject: Your Account Details from Bank Default Environment
  activeBranches:
    - Phnom Penh
    - Kompong Cham
    - Battombong