version: "3.8"
services:
  configserver:
    image: bank/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - bank
  account:
    image: bank/account:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bank
    depends_on: 
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
networks:
  bank: